### ISSUE TITLE
Instructions and context

### ISSUE THREAD

**Issue by omarcostahamido** [Quantumland-art/qart#1]
Hi @ariannacrippa ,
I didn't notice that you had pushed commits, somehow github didn't notify me even though i am `watching` the repo.

shall we use the python notebook also to explain the code in there (which might be useful for some future presentation or writing)?

Btw, did you write this QFT explanation yourself?
https://github.com/Quantumland-art/qart/blob/30052c5503b05c410f5e49865bafbc57774f1922/QFT_test_qart.ipynb#L139-L164

And we may add something on the readme as well, at the very least how to get started.

I had the repo public so that you could find it, and i'm glad you were able to join and add commits easily. I noticed that @karljansen hasn't accepted the invitation yet. I will put repo private for the time being and we can put it public again a little later.

**TODO**
- [ ] make repo private
- [ ] add basic instructions on readme
- [ ] write explanation on notebook

**Comment by omarcostahamido** [comment]
@ariannacrippa 
Btw, did you write this QFT explanation yourself?
https://github.com/Quantumland-art/qart/blob/30052c5503b05c410f5e49865bafbc57774f1922/QFT_test_qart.ipynb#L139-L164

**Comment by omarcostahamido** [comment]
Ok, so I noticed that paulo already starred this and making repo private will loose that 😆 
Any opinions regarding the public/private visibility?

**Comment by karljansen** [comment]
Keeping it private for the moment would be the best solution for me. Yes, Paulo told me yesterday about our project …

Best,  Karl

**Comment by ariannacrippa** [comment]
> @ariannacrippa Btw, did you write this QFT explanation yourself?
> 
> https://github.com/Quantumland-art/qart/blob/30052c5503b05c410f5e49865bafbc57774f1922/QFT_test_qart.ipynb#L139-L164

I used chatgpt just to have a draft for the explanation but if we want to put it public I would suggest to use other resources ;) I will add comments in the notebook in the next days 👍
